version: "3.4"

services:
  one-hub:
    image: deanxv/done-hub:latest
    container_name: done-hub
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - SQL_DSN=${SQL_DSN} # 使用.env文件中的SQL_DSN变量
      # - REDIS_CONN_STRING=redis://:jhkdjhkjdhsIUTYURTU_CQPQ82@10.0.0.83:6379 # redis (请将 your_password 替换为实际的 Redis 密码)
      - SESSION_SECRET=random_string # 修改为随机字符串
      - USER_TOKEN_SECRET=random_string # 修改为随机字符串,32位以上
      - TZ=Asia/Shanghai
      # - HASHIDS_SALT=random_string # 可空，建议设置，字符串元素不能重复
    #      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
    #      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
    #      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
